import { StyleSheet } from 'react-native';
import { colors, typography, spacing, borderRadius, shadows } from '../../lib/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.cream,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontFamily: 'Nunito-Medium',
    fontSize: typography.textBase,
    color: colors.brownMuted,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    padding: spacing.space6,
    paddingTop: spacing.space10,
  },
  stepContainer: {
    flex: 1,
  },
  // Welcome
  welcomeContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.space16,
  },
  mascotContainer: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: colors.cream,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 4,
    borderColor: colors.brown,
    marginBottom: spacing.space8,
    overflow: 'hidden',
  },
  mascotImage: {
    width: 130,
    height: 130,
  },
  welcomeTitle: {
    fontFamily: 'Quicksand-Bold',
    fontSize: typography.text3xl,
    fontWeight: typography.fontBold,
    color: colors.brown,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textLg,
    color: colors.brownMuted,
    textAlign: 'center',
    marginTop: spacing.space4,
    lineHeight: typography.textLg * 1.5,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.space2,
    backgroundColor: colors.primary,
    paddingVertical: spacing.space4,
    paddingHorizontal: spacing.space8,
    borderRadius: borderRadius.full,
    borderWidth: 2,
    borderColor: colors.brown,
    ...shadows.sm,
  },
  primaryButtonText: {
    fontFamily: 'Nunito-Bold',
    fontSize: typography.textLg,
    fontWeight: typography.fontBold,
    color: colors.brown,
  },
  // Personalize
  questionText: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: typography.textXl,
    fontWeight: typography.fontSemibold,
    color: colors.brown,
    marginBottom: spacing.space4,
  },
  householdGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.space3,
    marginBottom: spacing.space8,
  },
  householdOption: {
    width: '47%',
    paddingVertical: spacing.space4,
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderColor: colors.brown,
    ...shadows.sm,
  },
  householdOptionSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.brown,
  },
  householdEmoji: {
    fontSize: 32,
    marginBottom: spacing.space2,
  },
  householdLabel: {
    fontFamily: 'Nunito-Medium',
    fontSize: typography.textSm,
    color: colors.brown,
    fontWeight: typography.fontMedium,
  },
  householdLabelSelected: {
    fontFamily: 'Nunito-Bold',
    fontWeight: typography.fontBold,
  },
  dietaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.space2,
    marginBottom: spacing.space8,
  },
  dietaryChip: {
    paddingVertical: spacing.space2,
    paddingHorizontal: spacing.space3,
    backgroundColor: colors.white,
    borderRadius: borderRadius.full,
    borderWidth: 2,
    borderColor: colors.brownMuted,
  },
  dietaryChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.brown,
  },
  dietaryChipText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
  },
  dietaryChipTextSelected: {
    fontFamily: 'Nunito-SemiBold',
    color: colors.brown,
    fontWeight: typography.fontSemibold,
  },
  actionRow: {
    alignItems: 'center',
    gap: spacing.space4,
  },
  skipLink: {
    paddingVertical: spacing.space3,
  },
  skipLinkText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
    textDecorationLine: 'underline',
  },
  // First Suggestion
  suggestionIntro: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: typography.textXl,
    fontWeight: typography.fontSemibold,
    color: colors.brown,
    textAlign: 'center',
    marginBottom: spacing.space6,
  },
  loadingCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.space8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: colors.brown,
  },
  recipeCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    borderWidth: 2,
    borderColor: colors.brown,
    overflow: 'hidden',
    marginBottom: spacing.space4,
    ...shadows.md,
  },
  recipeImage: {
    width: '100%',
    height: 180,
  },
  recipeContent: {
    padding: spacing.space4,
  },
  recipeTitle: {
    fontFamily: 'Quicksand-Bold',
    fontSize: typography.textXl,
    fontWeight: typography.fontBold,
    color: colors.brown,
    marginBottom: spacing.space2,
  },
  recipeMeta: {
    flexDirection: 'row',
    gap: spacing.space4,
    marginBottom: spacing.space3,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.space1,
  },
  metaText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
  },
  recipeTagline: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
    fontStyle: 'italic',
  },
  suggestionActions: {
    flexDirection: 'row',
    gap: spacing.space3,
    marginBottom: spacing.space6,
  },
  actionButtonOutline: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.space2,
    paddingVertical: spacing.space3,
    backgroundColor: colors.white,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.brown,
  },
  actionButtonOutlineText: {
    fontFamily: 'Nunito-Medium',
    fontSize: typography.textSm,
    color: colors.brown,
    fontWeight: typography.fontMedium,
  },
  actionButtonFilled: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.space2,
    paddingVertical: spacing.space3,
    backgroundColor: colors.primary,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.brown,
  },
  actionButtonFilledText: {
    fontFamily: 'Nunito-SemiBold',
    fontSize: typography.textSm,
    color: colors.brown,
    fontWeight: typography.fontSemibold,
  },
  divider: {
    height: 1,
    backgroundColor: colors.brownMuted,
    opacity: 0.2,
    marginVertical: spacing.space6,
  },
  betterSuggestionsPrompt: {
    alignItems: 'center',
    marginBottom: spacing.space4,
  },
  betterSuggestionsTitle: {
    fontFamily: 'Nunito-SemiBold',
    fontSize: typography.textLg,
    fontWeight: typography.fontSemibold,
    color: colors.brown,
    textAlign: 'center',
    marginTop: spacing.space2,
  },
  promptActions: {
    alignItems: 'center',
    gap: spacing.space3,
  },
  // Pantry Seed
  seedTitle: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: typography.textXl,
    fontWeight: typography.fontSemibold,
    color: colors.brown,
    marginBottom: spacing.space6,
  },
  seedOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    padding: spacing.space4,
    borderRadius: borderRadius.lg,
    borderWidth: 2,
    borderColor: colors.brown,
    marginBottom: spacing.space3,
    ...shadows.sm,
  },
  seedOptionIcon: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.coralLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.space4,
  },
  seedOptionContent: {
    flex: 1,
  },
  seedOptionTitle: {
    fontFamily: 'Nunito-Bold',
    fontSize: typography.textBase,
    fontWeight: typography.fontBold,
    color: colors.brown,
    marginBottom: 2,
  },
  seedOptionSubtitle: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
  },
  // Checklist
  checklistTitle: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: typography.textXl,
    fontWeight: typography.fontSemibold,
    color: colors.brown,
    marginBottom: spacing.space6,
  },
  ingredientCategory: {
    marginBottom: spacing.space6,
  },
  categoryTitle: {
    fontFamily: 'Nunito-Bold',
    fontSize: typography.textSm,
    fontWeight: typography.fontBold,
    color: colors.brown,
    marginBottom: spacing.space3,
    letterSpacing: 0.5,
  },
  ingredientGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.space2,
  },
  ingredientChip: {
    paddingVertical: spacing.space2,
    paddingHorizontal: spacing.space3,
    backgroundColor: colors.white,
    borderRadius: borderRadius.md,
    borderWidth: 2,
    borderColor: colors.brownMuted,
  },
  ingredientChipSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.brown,
  },
  ingredientChipText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
  },
  ingredientChipTextSelected: {
    fontFamily: 'Nunito-SemiBold',
    color: colors.brown,
    fontWeight: typography.fontSemibold,
  },
  checklistFooter: {
    marginTop: spacing.space4,
    alignItems: 'center',
    gap: spacing.space3,
  },
  selectedCount: {
    fontFamily: 'Nunito-Medium',
    fontSize: typography.textBase,
    color: colors.brown,
  },
  // Result
  resultHeader: {
    alignItems: 'center',
    marginBottom: spacing.space4,
  },
  resultEmoji: {
    fontSize: 48,
    marginBottom: spacing.space2,
  },
  resultTitle: {
    fontFamily: 'Quicksand-Bold',
    fontSize: typography.text2xl,
    fontWeight: typography.fontBold,
    color: colors.brown,
  },
  resultSubtitle: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textBase,
    color: colors.brownMuted,
    textAlign: 'center',
    marginBottom: spacing.space4,
  },
  matchBadge: {
    backgroundColor: colors.successBg,
    paddingVertical: 2,
    paddingHorizontal: spacing.space2,
    borderRadius: borderRadius.sm,
  },
  matchBadgeText: {
    fontFamily: 'Nunito-SemiBold',
    fontSize: typography.textSm,
    color: colors.success,
    fontWeight: typography.fontSemibold,
  },
  cookButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.space2,
    backgroundColor: colors.coral,
    paddingVertical: spacing.space4,
    borderRadius: borderRadius.full,
    borderWidth: 2,
    borderColor: colors.brown,
    ...shadows.sm,
  },
  cookButtonText: {
    fontFamily: 'Nunito-Bold',
    fontSize: typography.textLg,
    fontWeight: typography.fontBold,
    color: colors.white,
  },
  enterAppLink: {
    alignItems: 'center',
    paddingVertical: spacing.space4,
  },
  enterAppText: {
    fontFamily: 'Nunito-SemiBold',
    fontSize: typography.textBase,
    color: colors.coral,
    fontWeight: typography.fontSemibold,
  },
  // Subscription
  subTitle: {
    fontFamily: 'Quicksand-SemiBold',
    fontSize: typography.textXl,
    fontWeight: typography.fontSemibold,
    color: colors.brown,
    textAlign: 'center',
    marginBottom: spacing.space6,
  },
  trialCard: {
    backgroundColor: colors.white,
    borderRadius: borderRadius.xl,
    padding: spacing.space6,
    borderWidth: 2,
    borderColor: colors.coral,
    alignItems: 'center',
    ...shadows.md,
  },
  trialEmoji: {
    fontSize: 48,
    marginBottom: spacing.space2,
  },
  trialTitle: {
    fontFamily: 'Quicksand-Bold',
    fontSize: typography.textLg,
    fontWeight: typography.fontBold,
    color: colors.coral,
    marginBottom: spacing.space4,
  },
  trialFeatures: {
    width: '100%',
    marginBottom: spacing.space4,
  },
  trialFeatureItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.space3,
    paddingVertical: spacing.space2,
  },
  trialFeatureText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brown,
  },
  savingsCallout: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.space2,
    backgroundColor: colors.successBg,
    paddingVertical: spacing.space2,
    paddingHorizontal: spacing.space4,
    borderRadius: borderRadius.full,
    marginBottom: spacing.space3,
  },
  savingsText: {
    fontFamily: 'Nunito-SemiBold',
    fontSize: typography.textSm,
    color: colors.success,
    fontWeight: typography.fontSemibold,
  },
  priceText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
    marginBottom: spacing.space4,
  },
  trialButton: {
    backgroundColor: colors.coral,
    paddingVertical: spacing.space4,
    paddingHorizontal: spacing.space6,
    borderRadius: borderRadius.full,
    borderWidth: 2,
    borderColor: colors.brown,
    width: '100%',
    alignItems: 'center',
  },
  trialButtonText: {
    fontFamily: 'Nunito-Bold',
    fontSize: typography.textBase,
    fontWeight: typography.fontBold,
    color: colors.white,
  },
  freeLink: {
    alignItems: 'center',
    paddingVertical: spacing.space6,
  },
  freeLinkText: {
    fontFamily: 'Nunito-Regular',
    fontSize: typography.textSm,
    color: colors.brownMuted,
  },
});
